Catch2 update
- update from v3.0.1 to v3.4.0 to fix compilation issues on new compilers
  error: no type named 'uint64_t' in namespace 'std'
- change compile and cppcheck flags for Catch2 to suppress warnings